### ISSUE TITLE
Is there a listing of known pages where this scraper works?

### ISSUE THREAD

**Issue by datatalking** [PaulMcInnis/JobFunnel#160] opened 2023-02-14 03:03 UTC
**Is your feature request related to a problem? Please describe.**
I was looking to see what job boards or webpages this scraper is known to be currently working.

**Describe the solution you'd like**
This scraper works on linkedin.com, monster.com, dice.com and we are having some CAPTCHA issues on indeed.com so about 20% failure rate.

**Describe alternatives you've considered**
I've been building a tool to pull job information out of html links and found your repo, so i'm curious what you have found that works

**Comment by PaulMcInnis** [comment] 2023-02-14 17:36
hey, this was designed to work with indeed and monster specifically, but as you are aware there are issues with captcha, #154 

closing this as a duplicate of ^

**Closed by PaulMcInnis** 2023-02-14 17:36 UTC
Labels: enhancement
