### ISSUE TITLE
AttributeError: module 'os' has no attribute 'add_dll_directory'

### ISSUE THREAD

**Issue by rrickgauer** [PaulMcInnis/JobFunnel#43] opened 2020-01-07 06:38 UTC
I just successfully installed it via: 
`pip install git+https://github.com/PaulMcInnis/JobFunnel.git`

However, when I entered `funnel --help` it gave me the error: 
`AttributeError: module 'os' has no attribute 'add_dll_directory'`

**Comment by rrickgauer** [comment] 2020-01-07 06:39
Full message:

`C:\Users\rrick>funnel --help
Traceback (most recent call last):
  File "c:\users\rrick\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\rrick\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\rrick\AppData\Local\Programs\Python\Python38\Scripts\funnel.exe\__main__.py", line 4, in <module>
  File "c:\users\rrick\appdata\local\programs\python\python38\lib\site-packages\jobfunnel\__main__.py", line 8, in <module>
    from .jobfunnel import JobFunnel
  File "c:\users\rrick\appdata\local\programs\python\python38\lib\site-packages\jobfunnel\jobfunnel.py", line 19, in <module>
    from .tools.delay import delay_alg
  File "c:\users\rrick\appdata\local\programs\python\python38\lib\site-packages\jobfunnel\tools\delay.py", line 7, in <module>
    from numpy import arange
  File "c:\users\rrick\appdata\local\programs\python\python38\lib\site-packages\numpy\__init__.py", line 126, in <module>
    from numpy.__config__ import show as show_config
  File "c:\users\rrick\appdata\local\programs\python\python38\lib\site-packages\numpy\__config__.py", line 13, in <module>
    os.add_dll_directory(extra_dll_dir)
AttributeError: module 'os' has no attribute 'add_dll_directory'`

**Comment by PaulMcInnis** [comment] 2020-01-07 13:50
Hmm ok. Ill have to test this in windows myself and see if I can replicate it.

**Comment by rodhod** [comment] 2020-01-09 18:42
the `os.add_dll_directory()` function was added in python 3.8, its supposed to make resolving dll files in windows smoother.

i ran into a similar error installing the VS Code Editior and used [this](https://community.platformio.org/t/cannot-install-win-10-vs-code/10729) to fix it.
it seems this error could be caused by a "funky" python install, maybe and alpha or beta version

**Comment by studentbrad** [comment] 2020-01-10 18:06
It seems this issue is outside the scope of JobFunnel.  Don’t use alpha or beta releases of Python3.8.  Can this issue be closed?

**Comment by PaulMcInnis** [comment] 2020-01-10 19:09
I also was unable to replicate this. Sorry, @rrickgauer - this appears to be a configuration issue with your environment. 

Recommend trying out installation in a virtual environment

**Closed by PaulMcInnis** 2020-01-10 19:09 UTC
Labels: bug, help wanted
