### ISSUE TITLE
JobFunnel: Failed to scrape jobs for IndeedScraperUSAEng

### ISSUE THREAD

**Issue by evb-gh** [PaulMcInnis/JobFunnel#137] opened 2021-03-17 01:37 UTC
#### Description
Running `funnel` with  `load -s settings_USA.yml` gives the following error:
```
[2021-03-16 18:34:58,123] [INFO] JobFunnel: Scraping local providers with: ['IndeedScraperUSAEng']
[2021-03-16 18:34:59,720] [ERROR] JobFunnel: Failed to scrape jobs for IndeedScraperUSAEng
[2021-03-16 18:34:59,720] [INFO] JobFunnel: Completed all scraping, found 0 new jobs.
[2021-03-16 18:34:59,882] [INFO] JobFunnel: Done. View your current jobs in demo_job_search_results/demo_search.csv

``` 
#### Environment

* Build: 3.0.1
* macOS 10.14

#### Would like to debug further but not sure how to do it.

**Comment by corielljacob** [comment] 2021-03-18 02:21
Also receiving this. Monster working fine but Indeed fails every time, even with different search keywords. Using DEBUG logging, I was able to get the URL it was trying to hit and it seemed fine.

Environment:
* Build 3.0.1
* Ubuntu 18.04.4 LTS
* Python 3.9.2

**Comment by PaulMcInnis** [comment] 2021-03-24 12:48
Thanks for opening an issue, I think we have some long outstanding issues with Parsing of the search URL for certain queries, if you are open to sharing your search URLs from logs it would be very helpful to identify what the issue is.

We current have CI for the US Indeed scraper but it only performs a basic search.

**Comment by corielljacob** [comment] 2021-03-24 14:34
Sure. My jobfunnel has also been failing the Monster scrape the past few days (using crontab to run once daily). I would also try and test if I can but I'm not very familiar with python and I couldnt figure out how to run from PyCharm with the source 😅
URL: https://www.indeed.com/jobs?q=Software Engineer&l=tulsa%2C+OK&radius=25&limit=50&filter=0
![JobFunnel](https://user-images.githubusercontent.com/32170426/112328086-fc834d80-8c83-11eb-9226-84ee1ae02a6d.PNG)

**Comment by PaulMcInnis** [comment] 2021-03-24 16:22
Ok, yeah looks like we need to improve the url parsing! Can you try instead searching for two separate keywords, like this: 
‘’’
- Software
- Engineer
‘’’

**Comment by PaulMcInnis** [comment] 2021-03-24 16:24
Oh i see that you tried with a single keyword as well, ok. I think this might be some other issue. 

One thing to try is to use current master of this repo. You can do that by installing it in place with, `pip install -e <path to this repo>`

**Comment by corielljacob** [comment] 2021-03-24 16:33
Went ahead and added the keywords separately like you mentioned anyway as well as installing the current master. However, it looks like I was already using master and looks like no change
![image](https://user-images.githubusercontent.com/32170426/112347339-c13d4a80-8c94-11eb-855b-67738821d45b.png)

**Comment by PaulMcInnis** [comment] 2021-03-24 16:54
Ah ok, thanks for being so responsive, we’ll have to take a deeper look. 

If you are feeling confident I invite you to break execution in the scraper where we collect the number of pages of results from the search url, I suspect the issue is there since it ends up scraping no jobs.

**Comment by corielljacob** [comment] 2021-03-24 18:05
I would be interested in doing some debugging, but I may need some advice with how I can do so from something like PyCharm (open to another IDE you recommend). This is a tad out of scope for the issue so pardon my intrusion.
I am trying to run JobFunnel-master\jobfunnel\__main__.py\ but doing so gets me an import error
![image](https://user-images.githubusercontent.com/32170426/112361303-3adb3580-8ca1-11eb-92b6-fc36999703d1.png)

Like I mentioned, I'm not super familiar with running python, especially in a project like this so this may be completely the wrong place to try and start running 😅 but if you can point me in the right direction for how I might get to a point where I can set breakpoints and such, I'd be happy to play around.

**Comment by PaulMcInnis** [comment] 2021-03-24 18:08
Unfortunately PyCharm doesn't work for this project due to use of abstract base classes. 

The best way to debug is to add a `import pdb; pdb.set_trace()` in the code where you would like to debug

then you have access to a complete python interpreter, i.e. `pp var_im_interested_in`

**Comment by marchbnr** [comment] 2021-03-25 14:48
You should be able to debug modules, such as jobfunnel, in pycharm like this:
https://stackoverflow.com/a/51268846

**Comment by evb-gh** [comment] 2021-03-29 15:57
If anyone reading this that has the time and knowledge can I ask you to write a step by step example of how to debug this code?
I would like to understand how to debug this repo by running it from a local directory with either pyCharm, cli or emacs.

**Comment by PaulMcInnis** [comment] 2021-03-29 16:02
RE pycharm, users have had issues using it with this repository in the past due to the ABC implementation: #24 

I highly recommend just adding the line `import pdb; pdb.set_trace()` anywhere in the base scraper or indeed scraper and playing around with the available methods and variables (`pp vars(self)`)

**Comment by evb-gh** [comment] 2021-03-29 16:10
Thanks for the quick reply. I apologize if my questions seem lazy (I have very little experience with python) but how do I run the code with test parameters (location, keywords) from local cloned repository?

**Comment by PaulMcInnis** [comment] 2021-03-29 16:12
> Thanks for the quick reply. I apologize if my questions seem lazy (I have very little experience with python) but how do I run the code with test parameters (location, keywords) from local cloned repository?

totally fine, happy to help!

You should be able to run with test parameters by doing this:
```
wget https://git.io/JUWeP -O my_settings.yaml
funnel load -s my_settings.yaml
```

**Comment by evb-gh** [comment] 2021-03-29 16:24
Running `funnel load -s my_settings.yaml` doesn't it run the code from `/usr/local/bin/funnel` which then executes code form   `/usr/local/lib/python3.9/site-packages/jobfunnel`?
What I'm trying to do is:
1. Clone the repo locally to `~/jobfunnel`
2. Add `import pdb; pdb.set_trace()` to `indeed.py` or `base.py`
3. Run the code from `~/jobfunnel` with my_settings.yml

**Comment by PaulMcInnis** [comment] 2021-03-29 16:36
Right i recommend doing this to have a test version of jobfunnel:

1. git clone this repo somewhere
2.  checkout the branch you want to test
2. `virtualenv venv`
3. `source venv/bin/activate`
4. `pip3 install -e ./jobfunnel`

When done you can exit virtualenv with `deactivate`

**Comment by PaulMcInnis** [comment] 2021-03-29 23:39
Ok so i think the best place to start is indeed.ca line 303 in the current master, ```query_resp.find``` returns None

**Comment by PaulMcInnis** [comment] 2021-03-29 23:55
didn't mean to close this abruptly but I think the encoding was causing this. Please pull the latest changes and try, but this has resolved the issue on my end.

**Closed** 2021-03-29 23:54 UTC
Labels: bug
